### ISSUE TITLE
MechWarrior 3 music plays from left speaker only?

### ISSUE THREAD

**Issue by 8bitKittyKat** [ayuanx/ogg-winmm#14]
I tried using this with MechWarrior 3 and while the OGG music tracks would play, they only played out of the left speaker. I swapped to [dippy-dipper/ogg-winmm](https://github.com/dippy-dipper/ogg-winmm) (which this is forked from) and the issue was gone.

**Comment by ayuanx** [comment]
It is a bug of MechWarrior 3 itself.

For stereo audio sources, the volume of left and right channel can be independently controlled.

If an app/game ends out volume control command with volume level only corresponding to one channel, it is equivalent to mute the other channel.

Regarding the [dippy-dipper] one, it simply applies the left channel volume control to both channels, which itself is wrong, but coincidentally covers up this bug of MechWarrior 3.

**Comment by ayuanx** [comment]
Wait, I was wrong. I double checked the code.

The root cause is that although we do have separate L/R channel volume control capability, we never report it to the game, so the game thinks we only support mono volume control and does not bother to send out L/R stereo volume control.

Fixed in v2023.07.24
